# Site settings
title: My blog
email: rasmusolofssons@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello this is description
baseurl: "/rasmusolofssons" # the subpath of your site, e.g. /blog/
url: "rasmusolofssons.github.io" # the base hostname & protocol for your site
github_username:  rasmusolofssons

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
